/*
 * &copy Nicholas Prado, aka Nzen. But, ISC license.
 */
package ws.nzen.splaintime;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import javax.swing.LayoutStyle;
import javax.swing.SpinnerNumberModel;
import javax.swing.WindowConstants;

/**

 @author Nzen
 */
public class ConfigDialog extends javax.swing.JDialog {

    private SplainTime parent;
    private StPreference whatsWanted;

    /**
     Creates new form ConfigDialog
     */
    public ConfigDialog( SplainTime callee, boolean modal ) {
        super( callee, modal );
        whatsWanted = new StPreference();
        initComponents();
        parent = callee;
    }


    public ConfigDialog( JFrame whatever,
    		StPreference initialVals )
	{
		super( whatever, true );
		whatsWanted = initialVals;
        initComponents();
	}


    /**
     This method is called from within the constructor to initialize the form.
     WARNING: Do NOT modify this code. The content of this method is always
     regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgAdjust = new ButtonGroup();
        jrbTerseAdjust = new JRadioButton();
        jrbVerboseAdjust = new JRadioButton();
        btnSave = new JButton();
        btnCancel = new JButton();
        jspClicksFinish = new JSpinner();
        jLabel1 = new JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Config SplainTime");

        bgAdjust.add(jrbTerseAdjust);
        jrbTerseAdjust.setFont(new Font("Times New Roman", 0, 14)); // NOI18N
        jrbTerseAdjust.setText("Terse adjust");

        bgAdjust.add(jrbVerboseAdjust);
        jrbVerboseAdjust.setFont(new Font("Times New Roman", 0, 14)); // NOI18N
        jrbVerboseAdjust.setText("Verbose adjust");
        jrbVerboseAdjust.setToolTipText("");

        btnSave.setFont(new Font("Times New Roman", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.setToolTipText("Save settings");
        btnSave.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                pressedSave(evt);
            }
        });

        btnCancel.setFont(new Font("Times New Roman", 0, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setToolTipText("Close config");
        btnCancel.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                pressedCancel(evt);
            }
        });

        jspClicksFinish.setFont(new Font("Times New Roman", 0, 14)); // NOI18N
        jspClicksFinish.setModel(new SpinnerNumberModel(2, 1, 4, 1));
        jspClicksFinish.setToolTipText("Clicks to Finish");

        jLabel1.setFont(new Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Clicks to Finish");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jrbTerseAdjust, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrbVerboseAdjust, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancel))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jspClicksFinish, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(btnSave, GroupLayout.PREFERRED_SIZE, 71, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(jrbTerseAdjust)
                    .addComponent(jLabel1)
                    .addComponent(jspClicksFinish, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbVerboseAdjust)
                    .addComponent(btnCancel))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pressedSave(ActionEvent evt) {//GEN-FIRST:event_pressedSave
        boolean wantsTerseAdjOutput = jrbTerseAdjust.isSelected();
        int clicksToClose = (int)jspClicksFinish.getValue();
        whatsWanted.setFinishFuse( clicksToClose );
        setVisible( false );
    }//GEN-LAST:event_pressedSave

    private void pressedCancel(ActionEvent evt) {//GEN-FIRST:event_pressedCancel
        this.dispose();
    }//GEN-LAST:event_pressedCancel


    public StPreference getConfig()
    {
    	return whatsWanted;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ButtonGroup bgAdjust;
    private JButton btnCancel;
    private JButton btnSave;
    private JLabel jLabel1;
    private JRadioButton jrbTerseAdjust;
    private JRadioButton jrbVerboseAdjust;
    private JSpinner jspClicksFinish;
    // End of variables declaration//GEN-END:variables
}
