/*
 * This file is generated by jOOQ.
 */
package ws.nzen.tracking.splaintime.dao.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ws.nzen.tracking.splaintime.dao.jooq.tables.Databasechangeloglock;
import ws.nzen.tracking.splaintime.dao.jooq.tables.StCategory;
import ws.nzen.tracking.splaintime.dao.jooq.tables.StConfiguration;
import ws.nzen.tracking.splaintime.dao.jooq.tables.StHashingAlgorithm;
import ws.nzen.tracking.splaintime.dao.jooq.tables.StPerson;
import ws.nzen.tracking.splaintime.dao.jooq.tables.StRecordingDevice;
import ws.nzen.tracking.splaintime.dao.jooq.tables.StRecordingDeviceType;
import ws.nzen.tracking.splaintime.dao.jooq.tables.StTag;
import ws.nzen.tracking.splaintime.dao.jooq.tables.StTagCategory;
import ws.nzen.tracking.splaintime.dao.jooq.tables.StType;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1080051299;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.DATABASECHANGELOGLOCK</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = ws.nzen.tracking.splaintime.dao.jooq.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * Characterizaton of tag, ex break or cooking
     */
    public final StCategory ST_CATEGORY = ws.nzen.tracking.splaintime.dao.jooq.tables.StCategory.ST_CATEGORY;

    /**
     * Arbitrary attributes for the runtime
     */
    public final StConfiguration ST_CONFIGURATION = ws.nzen.tracking.splaintime.dao.jooq.tables.StConfiguration.ST_CONFIGURATION;

    /**
     * How we hashed the person password
     */
    public final StHashingAlgorithm ST_HASHING_ALGORITHM = ws.nzen.tracking.splaintime.dao.jooq.tables.StHashingAlgorithm.ST_HASHING_ALGORITHM;

    /**
     * ST only expects one, but thats fine
     */
    public final StPerson ST_PERSON = ws.nzen.tracking.splaintime.dao.jooq.tables.StPerson.ST_PERSON;

    /**
     * For representing the pc, phone that recorded tags
     */
    public final StRecordingDevice ST_RECORDING_DEVICE = ws.nzen.tracking.splaintime.dao.jooq.tables.StRecordingDevice.ST_RECORDING_DEVICE;

    /**
     * Computer; phone
     */
    public final StRecordingDeviceType ST_RECORDING_DEVICE_TYPE = ws.nzen.tracking.splaintime.dao.jooq.tables.StRecordingDeviceType.ST_RECORDING_DEVICE_TYPE;

    /**
     * The user entered text about what happened during that time
     */
    public final StTag ST_TAG = ws.nzen.tracking.splaintime.dao.jooq.tables.StTag.ST_TAG;

    /**
     * Categories of a tag
     */
    public final StTagCategory ST_TAG_CATEGORY = ws.nzen.tracking.splaintime.dao.jooq.tables.StTagCategory.ST_TAG_CATEGORY;

    /**
     * Descriptions that dont need type checking
     */
    public final StType ST_TYPE = ws.nzen.tracking.splaintime.dao.jooq.tables.StType.ST_TYPE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            StCategory.ST_CATEGORY,
            StConfiguration.ST_CONFIGURATION,
            StHashingAlgorithm.ST_HASHING_ALGORITHM,
            StPerson.ST_PERSON,
            StRecordingDevice.ST_RECORDING_DEVICE,
            StRecordingDeviceType.ST_RECORDING_DEVICE_TYPE,
            StTag.ST_TAG,
            StTagCategory.ST_TAG_CATEGORY,
            StType.ST_TYPE);
    }
}
