/*
 * &copy Nicholas Prado, aka Nzen. But, ISC license.
 */
package nzen;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import javax.swing.LayoutStyle;
import javax.swing.SpinnerNumberModel;
import javax.swing.WindowConstants;

/**

 @author Nzen
 */
public class ConfigDialog extends javax.swing.JDialog {

    private SplainTime parent;

    /**
     Creates new form ConfigDialog
     */
    public ConfigDialog( SplainTime callee, boolean modal ) {
        super( callee, modal );
        initComponents();
        parent = callee;
    }

    /**
     This method is called from within the constructor to initialize the form.
     WARNING: Do NOT modify this code. The content of this method is always
     regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgAdjust = new ButtonGroup();
        jrbTerseAdjust = new JRadioButton();
        jrbVerboseAdjust = new JRadioButton();
        btnSave = new JButton();
        btnCancel = new JButton();
        jspClicksFinish = new JSpinner();
        jLabel1 = new JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Config SplainTime");

        bgAdjust.add(jrbTerseAdjust);
        jrbTerseAdjust.setFont(new Font("Times New Roman", 0, 14)); // NOI18N
        jrbTerseAdjust.setText("Terse adjust");

        bgAdjust.add(jrbVerboseAdjust);
        jrbVerboseAdjust.setFont(new Font("Times New Roman", 0, 14)); // NOI18N
        jrbVerboseAdjust.setText("Verbose adjust");
        jrbVerboseAdjust.setToolTipText("");

        btnSave.setFont(new Font("Times New Roman", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.setToolTipText("Save settings");
        btnSave.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                pressedSave(evt);
            }
        });

        btnCancel.setFont(new Font("Times New Roman", 0, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setToolTipText("Close config");
        btnCancel.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                pressedCancel(evt);
            }
        });

        jspClicksFinish.setFont(new Font("Times New Roman", 0, 14)); // NOI18N
        jspClicksFinish.setModel(new SpinnerNumberModel(2, 1, 4, 1));
        jspClicksFinish.setToolTipText("Clicks to Finish");

        jLabel1.setFont(new Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Clicks to Finish");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jrbTerseAdjust, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrbVerboseAdjust, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancel))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jspClicksFinish, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(btnSave, GroupLayout.PREFERRED_SIZE, 71, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(jrbTerseAdjust)
                    .addComponent(jLabel1)
                    .addComponent(jspClicksFinish, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbVerboseAdjust)
                    .addComponent(btnCancel))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pressedSave(ActionEvent evt) {//GEN-FIRST:event_pressedSave
        boolean wantsTerseAdjOutput = jrbTerseAdjust.isSelected();
        int clicksToClose = (int)jspClicksFinish.getValue();
        parent.applyConfig( wantsTerseAdjOutput, clicksToClose );
        this.dispose();
    }//GEN-LAST:event_pressedSave

    private void pressedCancel(ActionEvent evt) {//GEN-FIRST:event_pressedCancel
        this.dispose();
    }//GEN-LAST:event_pressedCancel

    /**
     @param args the command line arguments
     */
    public static void main( String args[] ) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() ) {
                if ( "Nimbus".equals( info.getName() ) ) {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        } catch ( ClassNotFoundException ex ) {
            java.util.logging.Logger.getLogger( ConfigDialog.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch ( InstantiationException ex ) {
            java.util.logging.Logger.getLogger( ConfigDialog.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch ( IllegalAccessException ex ) {
            java.util.logging.Logger.getLogger( ConfigDialog.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch ( javax.swing.UnsupportedLookAndFeelException ex ) {
            java.util.logging.Logger.getLogger( ConfigDialog.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater( new Runnable() {
            public void run() {
                ConfigDialog dialog = new ConfigDialog( new SplainTime(), true );
                dialog.addWindowListener( new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing( java.awt.event.WindowEvent e ) {
                        System.exit( 0 );
                    }
                } );
                dialog.setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ButtonGroup bgAdjust;
    private JButton btnCancel;
    private JButton btnSave;
    private JLabel jLabel1;
    private JRadioButton jrbTerseAdjust;
    private JRadioButton jrbVerboseAdjust;
    private JSpinner jspClicksFinish;
    // End of variables declaration//GEN-END:variables
}
