/*
 * This file is generated by jOOQ.
 */
package ws.nzen.tracking.splaintime.dao.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import ws.nzen.tracking.splaintime.dao.jooq.tables.StHashingAlgorithm;
import ws.nzen.tracking.splaintime.dao.jooq.tables.interfaces.IStHashingAlgorithm;


/**
 * How we hashed the person password
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StHashingAlgorithmRecord extends UpdatableRecordImpl<StHashingAlgorithmRecord> implements Record2<Integer, String>, IStHashingAlgorithm {

    private static final long serialVersionUID = -1167249369;

    /**
     * Setter for <code>PUBLIC.ST_HASHING_ALGORITHM.HASHING_ALGORITHM_ID</code>.
     */
    @Override
    public void setHashingAlgorithmId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.ST_HASHING_ALGORITHM.HASHING_ALGORITHM_ID</code>.
     */
    @Override
    public Integer getHashingAlgorithmId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.ST_HASHING_ALGORITHM.HASHING_ALGORITHM_DESC</code>.
     */
    @Override
    public void setHashingAlgorithmDesc(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.ST_HASHING_ALGORITHM.HASHING_ALGORITHM_DESC</code>.
     */
    @Override
    public String getHashingAlgorithmDesc() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return StHashingAlgorithm.ST_HASHING_ALGORITHM.HASHING_ALGORITHM_ID;
    }

    @Override
    public Field<String> field2() {
        return StHashingAlgorithm.ST_HASHING_ALGORITHM.HASHING_ALGORITHM_DESC;
    }

    @Override
    public Integer component1() {
        return getHashingAlgorithmId();
    }

    @Override
    public String component2() {
        return getHashingAlgorithmDesc();
    }

    @Override
    public Integer value1() {
        return getHashingAlgorithmId();
    }

    @Override
    public String value2() {
        return getHashingAlgorithmDesc();
    }

    @Override
    public StHashingAlgorithmRecord value1(Integer value) {
        setHashingAlgorithmId(value);
        return this;
    }

    @Override
    public StHashingAlgorithmRecord value2(String value) {
        setHashingAlgorithmDesc(value);
        return this;
    }

    @Override
    public StHashingAlgorithmRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IStHashingAlgorithm from) {
        setHashingAlgorithmId(from.getHashingAlgorithmId());
        setHashingAlgorithmDesc(from.getHashingAlgorithmDesc());
    }

    @Override
    public <E extends IStHashingAlgorithm> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StHashingAlgorithmRecord
     */
    public StHashingAlgorithmRecord() {
        super(StHashingAlgorithm.ST_HASHING_ALGORITHM);
    }

    /**
     * Create a detached, initialised StHashingAlgorithmRecord
     */
    public StHashingAlgorithmRecord(Integer hashingAlgorithmId, String hashingAlgorithmDesc) {
        super(StHashingAlgorithm.ST_HASHING_ALGORITHM);

        set(0, hashingAlgorithmId);
        set(1, hashingAlgorithmDesc);
    }
}
