/*
 * This file is generated by jOOQ.
 */
package ws.nzen.tracking.splaintime.dao.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import ws.nzen.tracking.splaintime.dao.jooq.tables.StTagCategory;


/**
 * Categories of a tag
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StTagCategoryRecord extends UpdatableRecordImpl<StTagCategoryRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 773220372;

    /**
     * Setter for <code>PUBLIC.ST_TAG_CATEGORY.TAG_ID</code>. fk
     */
    public void setTagId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.ST_TAG_CATEGORY.TAG_ID</code>. fk
     */
    public Integer getTagId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.ST_TAG_CATEGORY.CATEGORY_ID</code>. fk
     */
    public void setCategoryId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.ST_TAG_CATEGORY.CATEGORY_ID</code>. fk
     */
    public Integer getCategoryId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return StTagCategory.ST_TAG_CATEGORY.TAG_ID;
    }

    @Override
    public Field<Integer> field2() {
        return StTagCategory.ST_TAG_CATEGORY.CATEGORY_ID;
    }

    @Override
    public Integer component1() {
        return getTagId();
    }

    @Override
    public Integer component2() {
        return getCategoryId();
    }

    @Override
    public Integer value1() {
        return getTagId();
    }

    @Override
    public Integer value2() {
        return getCategoryId();
    }

    @Override
    public StTagCategoryRecord value1(Integer value) {
        setTagId(value);
        return this;
    }

    @Override
    public StTagCategoryRecord value2(Integer value) {
        setCategoryId(value);
        return this;
    }

    @Override
    public StTagCategoryRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StTagCategoryRecord
     */
    public StTagCategoryRecord() {
        super(StTagCategory.ST_TAG_CATEGORY);
    }

    /**
     * Create a detached, initialised StTagCategoryRecord
     */
    public StTagCategoryRecord(Integer tagId, Integer categoryId) {
        super(StTagCategory.ST_TAG_CATEGORY);

        set(0, tagId);
        set(1, categoryId);
    }
}
