/*
 * This file is generated by jOOQ.
 */
package ws.nzen.tracking.splaintime.dao.jooq.tables.pojos;


import javax.annotation.Generated;

import ws.nzen.tracking.splaintime.dao.jooq.tables.interfaces.IStRecordingDeviceType;


/**
 * Computer; phone
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StRecordingDeviceType implements IStRecordingDeviceType {

    private static final long serialVersionUID = 6133753;

    private Integer recordingDeviceTypeId;
    private String  recordingDeviceTypeDesc;

    public StRecordingDeviceType() {}

    public StRecordingDeviceType(IStRecordingDeviceType value) {
        this.recordingDeviceTypeId = value.getRecordingDeviceTypeId();
        this.recordingDeviceTypeDesc = value.getRecordingDeviceTypeDesc();
    }

    public StRecordingDeviceType(
        Integer recordingDeviceTypeId,
        String  recordingDeviceTypeDesc
    ) {
        this.recordingDeviceTypeId = recordingDeviceTypeId;
        this.recordingDeviceTypeDesc = recordingDeviceTypeDesc;
    }

    @Override
    public Integer getRecordingDeviceTypeId() {
        return this.recordingDeviceTypeId;
    }

    @Override
    public void setRecordingDeviceTypeId(Integer recordingDeviceTypeId) {
        this.recordingDeviceTypeId = recordingDeviceTypeId;
    }

    @Override
    public String getRecordingDeviceTypeDesc() {
        return this.recordingDeviceTypeDesc;
    }

    @Override
    public void setRecordingDeviceTypeDesc(String recordingDeviceTypeDesc) {
        this.recordingDeviceTypeDesc = recordingDeviceTypeDesc;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StRecordingDeviceType (");

        sb.append(recordingDeviceTypeId);
        sb.append(", ").append(recordingDeviceTypeDesc);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IStRecordingDeviceType from) {
        setRecordingDeviceTypeId(from.getRecordingDeviceTypeId());
        setRecordingDeviceTypeDesc(from.getRecordingDeviceTypeDesc());
    }

    @Override
    public <E extends IStRecordingDeviceType> E into(E into) {
        into.from(this);
        return into;
    }
}
