/*
 * This file is generated by jOOQ.
 */
package ws.nzen.tracking.splaintime.dao.jooq.tables.pojos;


import java.time.OffsetDateTime;

import javax.annotation.Generated;

import ws.nzen.tracking.splaintime.dao.jooq.tables.interfaces.IStTag;


/**
 * The user entered text about what happened during that time
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StTag implements IStTag {

    private static final long serialVersionUID = 157981946;

    private Integer        tagId;
    private OffsetDateTime happenedWhen;
    private OffsetDateTime adjustedWhen;
    private Integer        recordingDeviceId;
    private Integer        personId;
    private String         tagValue;
    private Boolean        adjustedWithHhmm;

    public StTag() {}

    public StTag(IStTag value) {
        this.tagId = value.getTagId();
        this.happenedWhen = value.getHappenedWhen();
        this.adjustedWhen = value.getAdjustedWhen();
        this.recordingDeviceId = value.getRecordingDeviceId();
        this.personId = value.getPersonId();
        this.tagValue = value.getTagValue();
        this.adjustedWithHhmm = value.getAdjustedWithHhmm();
    }

    public StTag(
        Integer        tagId,
        OffsetDateTime happenedWhen,
        OffsetDateTime adjustedWhen,
        Integer        recordingDeviceId,
        Integer        personId,
        String         tagValue,
        Boolean        adjustedWithHhmm
    ) {
        this.tagId = tagId;
        this.happenedWhen = happenedWhen;
        this.adjustedWhen = adjustedWhen;
        this.recordingDeviceId = recordingDeviceId;
        this.personId = personId;
        this.tagValue = tagValue;
        this.adjustedWithHhmm = adjustedWithHhmm;
    }

    @Override
    public Integer getTagId() {
        return this.tagId;
    }

    @Override
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    @Override
    public OffsetDateTime getHappenedWhen() {
        return this.happenedWhen;
    }

    @Override
    public void setHappenedWhen(OffsetDateTime happenedWhen) {
        this.happenedWhen = happenedWhen;
    }

    @Override
    public OffsetDateTime getAdjustedWhen() {
        return this.adjustedWhen;
    }

    @Override
    public void setAdjustedWhen(OffsetDateTime adjustedWhen) {
        this.adjustedWhen = adjustedWhen;
    }

    @Override
    public Integer getRecordingDeviceId() {
        return this.recordingDeviceId;
    }

    @Override
    public void setRecordingDeviceId(Integer recordingDeviceId) {
        this.recordingDeviceId = recordingDeviceId;
    }

    @Override
    public Integer getPersonId() {
        return this.personId;
    }

    @Override
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }

    @Override
    public String getTagValue() {
        return this.tagValue;
    }

    @Override
    public void setTagValue(String tagValue) {
        this.tagValue = tagValue;
    }

    @Override
    public Boolean getAdjustedWithHhmm() {
        return this.adjustedWithHhmm;
    }

    @Override
    public void setAdjustedWithHhmm(Boolean adjustedWithHhmm) {
        this.adjustedWithHhmm = adjustedWithHhmm;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StTag (");

        sb.append(tagId);
        sb.append(", ").append(happenedWhen);
        sb.append(", ").append(adjustedWhen);
        sb.append(", ").append(recordingDeviceId);
        sb.append(", ").append(personId);
        sb.append(", ").append(tagValue);
        sb.append(", ").append(adjustedWithHhmm);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IStTag from) {
        setTagId(from.getTagId());
        setHappenedWhen(from.getHappenedWhen());
        setAdjustedWhen(from.getAdjustedWhen());
        setRecordingDeviceId(from.getRecordingDeviceId());
        setPersonId(from.getPersonId());
        setTagValue(from.getTagValue());
        setAdjustedWithHhmm(from.getAdjustedWithHhmm());
    }

    @Override
    public <E extends IStTag> E into(E into) {
        into.from(this);
        return into;
    }
}
