/*
 * This file is generated by jOOQ.
 */
package ws.nzen.tracking.splaintime.dao.jooq.tables.pojos;


import javax.annotation.Generated;

import ws.nzen.tracking.splaintime.dao.jooq.tables.interfaces.IStTagCategory;


/**
 * Categories of a tag
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StTagCategory implements IStTagCategory {

    private static final long serialVersionUID = -775901337;

    private Integer tagId;
    private Integer categoryId;

    public StTagCategory() {}

    public StTagCategory(IStTagCategory value) {
        this.tagId = value.getTagId();
        this.categoryId = value.getCategoryId();
    }

    public StTagCategory(
        Integer tagId,
        Integer categoryId
    ) {
        this.tagId = tagId;
        this.categoryId = categoryId;
    }

    @Override
    public Integer getTagId() {
        return this.tagId;
    }

    @Override
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    @Override
    public Integer getCategoryId() {
        return this.categoryId;
    }

    @Override
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StTagCategory (");

        sb.append(tagId);
        sb.append(", ").append(categoryId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IStTagCategory from) {
        setTagId(from.getTagId());
        setCategoryId(from.getCategoryId());
    }

    @Override
    public <E extends IStTagCategory> E into(E into) {
        into.from(this);
        return into;
    }
}
