/*
 * This file is generated by jOOQ.
 */
package ws.nzen.tracking.splaintime.dao.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Arbitrary attributes for the runtime
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IStConfiguration extends Serializable {

    /**
     * Setter for <code>PUBLIC.ST_CONFIGURATION.CONFIGURATION_ID</code>.
     */
    public void setConfigurationId(Integer value);

    /**
     * Getter for <code>PUBLIC.ST_CONFIGURATION.CONFIGURATION_ID</code>.
     */
    public Integer getConfigurationId();

    /**
     * Setter for <code>PUBLIC.ST_CONFIGURATION.CONFIGURATION_DESC</code>.
     */
    public void setConfigurationDesc(String value);

    /**
     * Getter for <code>PUBLIC.ST_CONFIGURATION.CONFIGURATION_DESC</code>.
     */
    public String getConfigurationDesc();

    /**
     * Setter for <code>PUBLIC.ST_CONFIGURATION.TYPE_ID</code>. fk; redundant
     */
    public void setTypeId(Integer value);

    /**
     * Getter for <code>PUBLIC.ST_CONFIGURATION.TYPE_ID</code>. fk; redundant
     */
    public Integer getTypeId();

    /**
     * Setter for <code>PUBLIC.ST_CONFIGURATION.RECORDING_DEVICE_ID</code>. fk; ex to enable an easier undo string on a phone
     */
    public void setRecordingDeviceId(Integer value);

    /**
     * Getter for <code>PUBLIC.ST_CONFIGURATION.RECORDING_DEVICE_ID</code>. fk; ex to enable an easier undo string on a phone
     */
    public Integer getRecordingDeviceId();

    /**
     * Setter for <code>PUBLIC.ST_CONFIGURATION.TEXTUAL_VALUE</code>. Large, in case ST allows custom datetime format
     */
    public void setTextualValue(String value);

    /**
     * Getter for <code>PUBLIC.ST_CONFIGURATION.TEXTUAL_VALUE</code>. Large, in case ST allows custom datetime format
     */
    public String getTextualValue();

    /**
     * Setter for <code>PUBLIC.ST_CONFIGURATION.INTEGRAL_VALUE</code>.
     */
    public void setIntegralValue(Integer value);

    /**
     * Getter for <code>PUBLIC.ST_CONFIGURATION.INTEGRAL_VALUE</code>.
     */
    public Integer getIntegralValue();

    /**
     * Setter for <code>PUBLIC.ST_CONFIGURATION.BINARY_VALUE</code>.
     */
    public void setBinaryValue(Boolean value);

    /**
     * Getter for <code>PUBLIC.ST_CONFIGURATION.BINARY_VALUE</code>.
     */
    public Boolean getBinaryValue();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IStConfiguration
     */
    public void from(ws.nzen.tracking.splaintime.dao.jooq.tables.interfaces.IStConfiguration from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IStConfiguration
     */
    public <E extends ws.nzen.tracking.splaintime.dao.jooq.tables.interfaces.IStConfiguration> E into(E into);
}
