/*
 * This file is generated by jOOQ.
 */
package ws.nzen.tracking.splaintime.dao.jooq.tables.interfaces;


import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.Generated;


/**
 * Characterizaton of tag, ex break or cooking
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IStCategory extends Serializable {

    /**
     * Setter for <code>PUBLIC.ST_CATEGORY.CATEGORY_ID</code>.
     */
    public void setCategoryId(Integer value);

    /**
     * Getter for <code>PUBLIC.ST_CATEGORY.CATEGORY_ID</code>.
     */
    public Integer getCategoryId();

    /**
     * Setter for <code>PUBLIC.ST_CATEGORY.CATEGORY_DESC</code>.
     */
    public void setCategoryDesc(String value);

    /**
     * Getter for <code>PUBLIC.ST_CATEGORY.CATEGORY_DESC</code>.
     */
    public String getCategoryDesc();

    /**
     * Setter for <code>PUBLIC.ST_CATEGORY.EXPIRES_WHEN</code>.
     */
    public void setExpiresWhen(OffsetDateTime value);

    /**
     * Getter for <code>PUBLIC.ST_CATEGORY.EXPIRES_WHEN</code>.
     */
    public OffsetDateTime getExpiresWhen();

    /**
     * Setter for <code>PUBLIC.ST_CATEGORY.TYPE_ID</code>. fk
     */
    public void setTypeId(Integer value);

    /**
     * Getter for <code>PUBLIC.ST_CATEGORY.TYPE_ID</code>. fk
     */
    public Integer getTypeId();

    /**
     * Setter for <code>PUBLIC.ST_CATEGORY.PARENT_ID</code>. fk
     */
    public void setParentId(Integer value);

    /**
     * Getter for <code>PUBLIC.ST_CATEGORY.PARENT_ID</code>. fk
     */
    public Integer getParentId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IStCategory
     */
    public void from(ws.nzen.tracking.splaintime.dao.jooq.tables.interfaces.IStCategory from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IStCategory
     */
    public <E extends ws.nzen.tracking.splaintime.dao.jooq.tables.interfaces.IStCategory> E into(E into);
}
