/*
 * This file is generated by jOOQ.
 */
package ws.nzen.tracking.splaintime.dao.jooq.tables.interfaces;


import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.Generated;


/**
 * ST only expects one, but thats fine
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IStPerson extends Serializable {

    /**
     * Setter for <code>PUBLIC.ST_PERSON.PERSON_ID</code>.
     */
    public void setPersonId(Integer value);

    /**
     * Getter for <code>PUBLIC.ST_PERSON.PERSON_ID</code>.
     */
    public Integer getPersonId();

    /**
     * Setter for <code>PUBLIC.ST_PERSON.PERSON_DESC</code>.
     */
    public void setPersonDesc(String value);

    /**
     * Getter for <code>PUBLIC.ST_PERSON.PERSON_DESC</code>.
     */
    public String getPersonDesc();

    /**
     * Setter for <code>PUBLIC.ST_PERSON.PASSWORD_HASH</code>.
     */
    public void setPasswordHash(String value);

    /**
     * Getter for <code>PUBLIC.ST_PERSON.PASSWORD_HASH</code>.
     */
    public String getPasswordHash();

    /**
     * Setter for <code>PUBLIC.ST_PERSON.PASSWORD_SALT</code>. Preferably unique
     */
    public void setPasswordSalt(String value);

    /**
     * Getter for <code>PUBLIC.ST_PERSON.PASSWORD_SALT</code>. Preferably unique
     */
    public String getPasswordSalt();

    /**
     * Setter for <code>PUBLIC.ST_PERSON.HASHING_ALGORITHM_ID</code>. fk
     */
    public void setHashingAlgorithmId(Integer value);

    /**
     * Getter for <code>PUBLIC.ST_PERSON.HASHING_ALGORITHM_ID</code>. fk
     */
    public Integer getHashingAlgorithmId();

    /**
     * Setter for <code>PUBLIC.ST_PERSON.ADDED_WHEN</code>.
     */
    public void setAddedWhen(OffsetDateTime value);

    /**
     * Getter for <code>PUBLIC.ST_PERSON.ADDED_WHEN</code>.
     */
    public OffsetDateTime getAddedWhen();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IStPerson
     */
    public void from(ws.nzen.tracking.splaintime.dao.jooq.tables.interfaces.IStPerson from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IStPerson
     */
    public <E extends ws.nzen.tracking.splaintime.dao.jooq.tables.interfaces.IStPerson> E into(E into);
}
