/*
 * This file is generated by jOOQ.
 */
package ws.nzen.tracking.splaintime.dao.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * For representing the pc, phone that recorded tags
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IStRecordingDevice extends Serializable {

    /**
     * Setter for <code>PUBLIC.ST_RECORDING_DEVICE.RECORDING_DEVICE_ID</code>.
     */
    public void setRecordingDeviceId(Integer value);

    /**
     * Getter for <code>PUBLIC.ST_RECORDING_DEVICE.RECORDING_DEVICE_ID</code>.
     */
    public Integer getRecordingDeviceId();

    /**
     * Setter for <code>PUBLIC.ST_RECORDING_DEVICE.RECORDING_DEVICE_DESC</code>.
     */
    public void setRecordingDeviceDesc(String value);

    /**
     * Getter for <code>PUBLIC.ST_RECORDING_DEVICE.RECORDING_DEVICE_DESC</code>.
     */
    public String getRecordingDeviceDesc();

    /**
     * Setter for <code>PUBLIC.ST_RECORDING_DEVICE.RECORDING_DEVICE_TYPE_ID</code>. fk; assume pc
     */
    public void setRecordingDeviceTypeId(Integer value);

    /**
     * Getter for <code>PUBLIC.ST_RECORDING_DEVICE.RECORDING_DEVICE_TYPE_ID</code>. fk; assume pc
     */
    public Integer getRecordingDeviceTypeId();

    /**
     * Setter for <code>PUBLIC.ST_RECORDING_DEVICE.HOME_DIR_GUID</code>.
     */
    public void setHomeDirGuid(String value);

    /**
     * Getter for <code>PUBLIC.ST_RECORDING_DEVICE.HOME_DIR_GUID</code>.
     */
    public String getHomeDirGuid();

    /**
     * Setter for <code>PUBLIC.ST_RECORDING_DEVICE.IPV4_ADDRESS</code>. as an assist to initial user identification
     */
    public void setIpv4Address(String value);

    /**
     * Getter for <code>PUBLIC.ST_RECORDING_DEVICE.IPV4_ADDRESS</code>. as an assist to initial user identification
     */
    public String getIpv4Address();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IStRecordingDevice
     */
    public void from(ws.nzen.tracking.splaintime.dao.jooq.tables.interfaces.IStRecordingDevice from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IStRecordingDevice
     */
    public <E extends ws.nzen.tracking.splaintime.dao.jooq.tables.interfaces.IStRecordingDevice> E into(E into);
}
