/*
 * This file is generated by jOOQ.
 */
package ws.nzen.tracking.splaintime.dao.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Computer; phone
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IStRecordingDeviceType extends Serializable {

    /**
     * Setter for <code>PUBLIC.ST_RECORDING_DEVICE_TYPE.RECORDING_DEVICE_TYPE_ID</code>.
     */
    public void setRecordingDeviceTypeId(Integer value);

    /**
     * Getter for <code>PUBLIC.ST_RECORDING_DEVICE_TYPE.RECORDING_DEVICE_TYPE_ID</code>.
     */
    public Integer getRecordingDeviceTypeId();

    /**
     * Setter for <code>PUBLIC.ST_RECORDING_DEVICE_TYPE.RECORDING_DEVICE_TYPE_DESC</code>.
     */
    public void setRecordingDeviceTypeDesc(String value);

    /**
     * Getter for <code>PUBLIC.ST_RECORDING_DEVICE_TYPE.RECORDING_DEVICE_TYPE_DESC</code>.
     */
    public String getRecordingDeviceTypeDesc();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IStRecordingDeviceType
     */
    public void from(ws.nzen.tracking.splaintime.dao.jooq.tables.interfaces.IStRecordingDeviceType from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IStRecordingDeviceType
     */
    public <E extends ws.nzen.tracking.splaintime.dao.jooq.tables.interfaces.IStRecordingDeviceType> E into(E into);
}
