/*
 * This file is generated by jOOQ.
 */
package ws.nzen.tracking.splaintime.dao.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Categories of a tag
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IStTagCategory extends Serializable {

    /**
     * Setter for <code>PUBLIC.ST_TAG_CATEGORY.TAG_ID</code>. fk
     */
    public void setTagId(Integer value);

    /**
     * Getter for <code>PUBLIC.ST_TAG_CATEGORY.TAG_ID</code>. fk
     */
    public Integer getTagId();

    /**
     * Setter for <code>PUBLIC.ST_TAG_CATEGORY.CATEGORY_ID</code>. fk
     */
    public void setCategoryId(Integer value);

    /**
     * Getter for <code>PUBLIC.ST_TAG_CATEGORY.CATEGORY_ID</code>. fk
     */
    public Integer getCategoryId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IStTagCategory
     */
    public void from(ws.nzen.tracking.splaintime.dao.jooq.tables.interfaces.IStTagCategory from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IStTagCategory
     */
    public <E extends ws.nzen.tracking.splaintime.dao.jooq.tables.interfaces.IStTagCategory> E into(E into);
}
