/*
 * This file is generated by jOOQ.
 */
package ws.nzen.tracking.splaintime.dao.jooq.tables.daos;


import java.time.OffsetDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import ws.nzen.tracking.splaintime.dao.jooq.tables.StCategory;
import ws.nzen.tracking.splaintime.dao.jooq.tables.records.StCategoryRecord;


/**
 * Characterizaton of tag, ex break or cooking
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StCategoryDao extends DAOImpl<StCategoryRecord, ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StCategory, Integer> {

    /**
     * Create a new StCategoryDao without any configuration
     */
    public StCategoryDao() {
        super(StCategory.ST_CATEGORY, ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StCategory.class);
    }

    /**
     * Create a new StCategoryDao with an attached configuration
     */
    public StCategoryDao(Configuration configuration) {
        super(StCategory.ST_CATEGORY, ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StCategory.class, configuration);
    }

    @Override
    public Integer getId(ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StCategory object) {
        return object.getCategoryId();
    }

    /**
     * Fetch records that have <code>CATEGORY_ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StCategory> fetchRangeOfCategoryId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(StCategory.ST_CATEGORY.CATEGORY_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>CATEGORY_ID IN (values)</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StCategory> fetchByCategoryId(Integer... values) {
        return fetch(StCategory.ST_CATEGORY.CATEGORY_ID, values);
    }

    /**
     * Fetch a unique record that has <code>CATEGORY_ID = value</code>
     */
    public ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StCategory fetchOneByCategoryId(Integer value) {
        return fetchOne(StCategory.ST_CATEGORY.CATEGORY_ID, value);
    }

    /**
     * Fetch records that have <code>CATEGORY_DESC BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StCategory> fetchRangeOfCategoryDesc(String lowerInclusive, String upperInclusive) {
        return fetchRange(StCategory.ST_CATEGORY.CATEGORY_DESC, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>CATEGORY_DESC IN (values)</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StCategory> fetchByCategoryDesc(String... values) {
        return fetch(StCategory.ST_CATEGORY.CATEGORY_DESC, values);
    }

    /**
     * Fetch records that have <code>EXPIRES_WHEN BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StCategory> fetchRangeOfExpiresWhen(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(StCategory.ST_CATEGORY.EXPIRES_WHEN, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>EXPIRES_WHEN IN (values)</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StCategory> fetchByExpiresWhen(OffsetDateTime... values) {
        return fetch(StCategory.ST_CATEGORY.EXPIRES_WHEN, values);
    }

    /**
     * Fetch records that have <code>TYPE_ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StCategory> fetchRangeOfTypeId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(StCategory.ST_CATEGORY.TYPE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>TYPE_ID IN (values)</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StCategory> fetchByTypeId(Integer... values) {
        return fetch(StCategory.ST_CATEGORY.TYPE_ID, values);
    }

    /**
     * Fetch records that have <code>PARENT_ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StCategory> fetchRangeOfParentId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(StCategory.ST_CATEGORY.PARENT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>PARENT_ID IN (values)</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StCategory> fetchByParentId(Integer... values) {
        return fetch(StCategory.ST_CATEGORY.PARENT_ID, values);
    }
}
