/*
 * This file is generated by jOOQ.
 */
package ws.nzen.tracking.splaintime.dao.jooq.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import ws.nzen.tracking.splaintime.dao.jooq.tables.StHashingAlgorithm;
import ws.nzen.tracking.splaintime.dao.jooq.tables.records.StHashingAlgorithmRecord;


/**
 * How we hashed the person password
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StHashingAlgorithmDao extends DAOImpl<StHashingAlgorithmRecord, ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StHashingAlgorithm, Integer> {

    /**
     * Create a new StHashingAlgorithmDao without any configuration
     */
    public StHashingAlgorithmDao() {
        super(StHashingAlgorithm.ST_HASHING_ALGORITHM, ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StHashingAlgorithm.class);
    }

    /**
     * Create a new StHashingAlgorithmDao with an attached configuration
     */
    public StHashingAlgorithmDao(Configuration configuration) {
        super(StHashingAlgorithm.ST_HASHING_ALGORITHM, ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StHashingAlgorithm.class, configuration);
    }

    @Override
    public Integer getId(ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StHashingAlgorithm object) {
        return object.getHashingAlgorithmId();
    }

    /**
     * Fetch records that have <code>HASHING_ALGORITHM_ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StHashingAlgorithm> fetchRangeOfHashingAlgorithmId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(StHashingAlgorithm.ST_HASHING_ALGORITHM.HASHING_ALGORITHM_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>HASHING_ALGORITHM_ID IN (values)</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StHashingAlgorithm> fetchByHashingAlgorithmId(Integer... values) {
        return fetch(StHashingAlgorithm.ST_HASHING_ALGORITHM.HASHING_ALGORITHM_ID, values);
    }

    /**
     * Fetch a unique record that has <code>HASHING_ALGORITHM_ID = value</code>
     */
    public ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StHashingAlgorithm fetchOneByHashingAlgorithmId(Integer value) {
        return fetchOne(StHashingAlgorithm.ST_HASHING_ALGORITHM.HASHING_ALGORITHM_ID, value);
    }

    /**
     * Fetch records that have <code>HASHING_ALGORITHM_DESC BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StHashingAlgorithm> fetchRangeOfHashingAlgorithmDesc(String lowerInclusive, String upperInclusive) {
        return fetchRange(StHashingAlgorithm.ST_HASHING_ALGORITHM.HASHING_ALGORITHM_DESC, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>HASHING_ALGORITHM_DESC IN (values)</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StHashingAlgorithm> fetchByHashingAlgorithmDesc(String... values) {
        return fetch(StHashingAlgorithm.ST_HASHING_ALGORITHM.HASHING_ALGORITHM_DESC, values);
    }
}
