/*
 * This file is generated by jOOQ.
 */
package ws.nzen.tracking.splaintime.dao.jooq.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import ws.nzen.tracking.splaintime.dao.jooq.tables.StRecordingDevice;
import ws.nzen.tracking.splaintime.dao.jooq.tables.records.StRecordingDeviceRecord;


/**
 * For representing the pc, phone that recorded tags
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StRecordingDeviceDao extends DAOImpl<StRecordingDeviceRecord, ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StRecordingDevice, Integer> {

    /**
     * Create a new StRecordingDeviceDao without any configuration
     */
    public StRecordingDeviceDao() {
        super(StRecordingDevice.ST_RECORDING_DEVICE, ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StRecordingDevice.class);
    }

    /**
     * Create a new StRecordingDeviceDao with an attached configuration
     */
    public StRecordingDeviceDao(Configuration configuration) {
        super(StRecordingDevice.ST_RECORDING_DEVICE, ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StRecordingDevice.class, configuration);
    }

    @Override
    public Integer getId(ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StRecordingDevice object) {
        return object.getRecordingDeviceId();
    }

    /**
     * Fetch records that have <code>RECORDING_DEVICE_ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StRecordingDevice> fetchRangeOfRecordingDeviceId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(StRecordingDevice.ST_RECORDING_DEVICE.RECORDING_DEVICE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>RECORDING_DEVICE_ID IN (values)</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StRecordingDevice> fetchByRecordingDeviceId(Integer... values) {
        return fetch(StRecordingDevice.ST_RECORDING_DEVICE.RECORDING_DEVICE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>RECORDING_DEVICE_ID = value</code>
     */
    public ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StRecordingDevice fetchOneByRecordingDeviceId(Integer value) {
        return fetchOne(StRecordingDevice.ST_RECORDING_DEVICE.RECORDING_DEVICE_ID, value);
    }

    /**
     * Fetch records that have <code>RECORDING_DEVICE_DESC BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StRecordingDevice> fetchRangeOfRecordingDeviceDesc(String lowerInclusive, String upperInclusive) {
        return fetchRange(StRecordingDevice.ST_RECORDING_DEVICE.RECORDING_DEVICE_DESC, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>RECORDING_DEVICE_DESC IN (values)</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StRecordingDevice> fetchByRecordingDeviceDesc(String... values) {
        return fetch(StRecordingDevice.ST_RECORDING_DEVICE.RECORDING_DEVICE_DESC, values);
    }

    /**
     * Fetch records that have <code>RECORDING_DEVICE_TYPE_ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StRecordingDevice> fetchRangeOfRecordingDeviceTypeId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(StRecordingDevice.ST_RECORDING_DEVICE.RECORDING_DEVICE_TYPE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>RECORDING_DEVICE_TYPE_ID IN (values)</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StRecordingDevice> fetchByRecordingDeviceTypeId(Integer... values) {
        return fetch(StRecordingDevice.ST_RECORDING_DEVICE.RECORDING_DEVICE_TYPE_ID, values);
    }

    /**
     * Fetch records that have <code>HOME_DIR_GUID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StRecordingDevice> fetchRangeOfHomeDirGuid(String lowerInclusive, String upperInclusive) {
        return fetchRange(StRecordingDevice.ST_RECORDING_DEVICE.HOME_DIR_GUID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>HOME_DIR_GUID IN (values)</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StRecordingDevice> fetchByHomeDirGuid(String... values) {
        return fetch(StRecordingDevice.ST_RECORDING_DEVICE.HOME_DIR_GUID, values);
    }

    /**
     * Fetch records that have <code>IPV4_ADDRESS BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StRecordingDevice> fetchRangeOfIpv4Address(String lowerInclusive, String upperInclusive) {
        return fetchRange(StRecordingDevice.ST_RECORDING_DEVICE.IPV4_ADDRESS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>IPV4_ADDRESS IN (values)</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StRecordingDevice> fetchByIpv4Address(String... values) {
        return fetch(StRecordingDevice.ST_RECORDING_DEVICE.IPV4_ADDRESS, values);
    }
}
