/*
 * This file is generated by jOOQ.
 */
package ws.nzen.tracking.splaintime.dao.jooq.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;

import ws.nzen.tracking.splaintime.dao.jooq.tables.StTagCategory;
import ws.nzen.tracking.splaintime.dao.jooq.tables.records.StTagCategoryRecord;


/**
 * Categories of a tag
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StTagCategoryDao extends DAOImpl<StTagCategoryRecord, ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StTagCategory, Record2<Integer, Integer>> {

    /**
     * Create a new StTagCategoryDao without any configuration
     */
    public StTagCategoryDao() {
        super(StTagCategory.ST_TAG_CATEGORY, ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StTagCategory.class);
    }

    /**
     * Create a new StTagCategoryDao with an attached configuration
     */
    public StTagCategoryDao(Configuration configuration) {
        super(StTagCategory.ST_TAG_CATEGORY, ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StTagCategory.class, configuration);
    }

    @Override
    public Record2<Integer, Integer> getId(ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StTagCategory object) {
        return compositeKeyRecord(object.getTagId(), object.getCategoryId());
    }

    /**
     * Fetch records that have <code>TAG_ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StTagCategory> fetchRangeOfTagId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(StTagCategory.ST_TAG_CATEGORY.TAG_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>TAG_ID IN (values)</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StTagCategory> fetchByTagId(Integer... values) {
        return fetch(StTagCategory.ST_TAG_CATEGORY.TAG_ID, values);
    }

    /**
     * Fetch records that have <code>CATEGORY_ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StTagCategory> fetchRangeOfCategoryId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(StTagCategory.ST_TAG_CATEGORY.CATEGORY_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>CATEGORY_ID IN (values)</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StTagCategory> fetchByCategoryId(Integer... values) {
        return fetch(StTagCategory.ST_TAG_CATEGORY.CATEGORY_ID, values);
    }
}
