/*
 * This file is generated by jOOQ.
 */
package ws.nzen.tracking.splaintime.dao.jooq.tables.daos;


import java.time.OffsetDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import ws.nzen.tracking.splaintime.dao.jooq.tables.StTag;
import ws.nzen.tracking.splaintime.dao.jooq.tables.records.StTagRecord;


/**
 * The user entered text about what happened during that time
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StTagDao extends DAOImpl<StTagRecord, ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StTag, Integer> {

    /**
     * Create a new StTagDao without any configuration
     */
    public StTagDao() {
        super(StTag.ST_TAG, ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StTag.class);
    }

    /**
     * Create a new StTagDao with an attached configuration
     */
    public StTagDao(Configuration configuration) {
        super(StTag.ST_TAG, ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StTag.class, configuration);
    }

    @Override
    public Integer getId(ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StTag object) {
        return object.getTagId();
    }

    /**
     * Fetch records that have <code>TAG_ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StTag> fetchRangeOfTagId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(StTag.ST_TAG.TAG_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>TAG_ID IN (values)</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StTag> fetchByTagId(Integer... values) {
        return fetch(StTag.ST_TAG.TAG_ID, values);
    }

    /**
     * Fetch a unique record that has <code>TAG_ID = value</code>
     */
    public ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StTag fetchOneByTagId(Integer value) {
        return fetchOne(StTag.ST_TAG.TAG_ID, value);
    }

    /**
     * Fetch records that have <code>HAPPENED_WHEN BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StTag> fetchRangeOfHappenedWhen(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(StTag.ST_TAG.HAPPENED_WHEN, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>HAPPENED_WHEN IN (values)</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StTag> fetchByHappenedWhen(OffsetDateTime... values) {
        return fetch(StTag.ST_TAG.HAPPENED_WHEN, values);
    }

    /**
     * Fetch records that have <code>ADJUSTED_WHEN BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StTag> fetchRangeOfAdjustedWhen(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(StTag.ST_TAG.ADJUSTED_WHEN, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ADJUSTED_WHEN IN (values)</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StTag> fetchByAdjustedWhen(OffsetDateTime... values) {
        return fetch(StTag.ST_TAG.ADJUSTED_WHEN, values);
    }

    /**
     * Fetch records that have <code>RECORDING_DEVICE_ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StTag> fetchRangeOfRecordingDeviceId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(StTag.ST_TAG.RECORDING_DEVICE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>RECORDING_DEVICE_ID IN (values)</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StTag> fetchByRecordingDeviceId(Integer... values) {
        return fetch(StTag.ST_TAG.RECORDING_DEVICE_ID, values);
    }

    /**
     * Fetch records that have <code>PERSON_ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StTag> fetchRangeOfPersonId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(StTag.ST_TAG.PERSON_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>PERSON_ID IN (values)</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StTag> fetchByPersonId(Integer... values) {
        return fetch(StTag.ST_TAG.PERSON_ID, values);
    }

    /**
     * Fetch records that have <code>TAG_VALUE BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StTag> fetchRangeOfTagValue(String lowerInclusive, String upperInclusive) {
        return fetchRange(StTag.ST_TAG.TAG_VALUE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>TAG_VALUE IN (values)</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StTag> fetchByTagValue(String... values) {
        return fetch(StTag.ST_TAG.TAG_VALUE, values);
    }

    /**
     * Fetch records that have <code>ADJUSTED_WITH_HHMM BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StTag> fetchRangeOfAdjustedWithHhmm(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(StTag.ST_TAG.ADJUSTED_WITH_HHMM, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ADJUSTED_WITH_HHMM IN (values)</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StTag> fetchByAdjustedWithHhmm(Boolean... values) {
        return fetch(StTag.ST_TAG.ADJUSTED_WITH_HHMM, values);
    }
}
