/*
 * This file is generated by jOOQ.
 */
package ws.nzen.tracking.splaintime.dao.jooq.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import ws.nzen.tracking.splaintime.dao.jooq.tables.StType;
import ws.nzen.tracking.splaintime.dao.jooq.tables.records.StTypeRecord;


/**
 * Descriptions that dont need type checking
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StTypeDao extends DAOImpl<StTypeRecord, ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StType, Integer> {

    /**
     * Create a new StTypeDao without any configuration
     */
    public StTypeDao() {
        super(StType.ST_TYPE, ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StType.class);
    }

    /**
     * Create a new StTypeDao with an attached configuration
     */
    public StTypeDao(Configuration configuration) {
        super(StType.ST_TYPE, ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StType.class, configuration);
    }

    @Override
    public Integer getId(ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StType object) {
        return object.getTypeId();
    }

    /**
     * Fetch records that have <code>TYPE_ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StType> fetchRangeOfTypeId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(StType.ST_TYPE.TYPE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>TYPE_ID IN (values)</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StType> fetchByTypeId(Integer... values) {
        return fetch(StType.ST_TYPE.TYPE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>TYPE_ID = value</code>
     */
    public ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StType fetchOneByTypeId(Integer value) {
        return fetchOne(StType.ST_TYPE.TYPE_ID, value);
    }

    /**
     * Fetch records that have <code>TYPE_DESC BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StType> fetchRangeOfTypeDesc(String lowerInclusive, String upperInclusive) {
        return fetchRange(StType.ST_TYPE.TYPE_DESC, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>TYPE_DESC IN (values)</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StType> fetchByTypeDesc(String... values) {
        return fetch(StType.ST_TYPE.TYPE_DESC, values);
    }

    /**
     * Fetch records that have <code>OWN_TYPE BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StType> fetchRangeOfOwnType(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(StType.ST_TYPE.OWN_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>OWN_TYPE IN (values)</code>
     */
    public List<ws.nzen.tracking.splaintime.dao.jooq.tables.pojos.StType> fetchByOwnType(Integer... values) {
        return fetch(StType.ST_TYPE.OWN_TYPE, values);
    }
}
